language: python
python:
  - "3.6"

services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run app sh -c "python3 manage.py test"

#If the script fails, then the build fails and we will be notified