# Generated by Django 2.2.1 on 2019-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
