# Generated by Django 2.2.1 on 2019-06-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190601_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='over',
        ),
    ]
