# Generated by Django 2.2.1 on 2019-06-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('over', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Location')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('text_on_board', models.CharField(max_length=3000)),
                ('time_taken', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lessons',
            field=models.ManyToManyField(to='core.Lesson'),
        ),
    ]
