# Generated by Django 2.2.1 on 2019-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190601_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(default=None),
        ),
    ]
